server:
  port: 9000
spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    consumer:
      group-id: chat-app
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        "specific.protobuf.value.type": com.github.cjmatta.kafka.connect.irc.MessageEvent$Message
    streams:
      application-id: chat-stream
      cleanup:
        on-startup: true  
      state-store-cache-max-size: 0      
      properties:
        "processing.guarantee": exactly_once_v2   
    properties:
      "schema.registry.url": http://localhost:8085

springdoc:
  swagger-ui:
    url: /openapi/chat.yml

topics:
  chat: chat
  filtered-chat: filtered-chat
  bad-words: badwords
  timeouts: timeouts

