# App
//TODO configure topics
chat.topics.in.chat=
chat.topics.out.input=

# Kafka
//TODO configure group-id

spring.kafka.properties.ssl.endpoint.identification.algorithm=https
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.bootstrap.servers=${KAFKA_SERVER}
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule   required username="${KAFKA_API_KEY}"   password="${KAFKA_API_SECRET}";
spring.kafka.properties.security.protocol=SASL_SSL

# Kafka Serde
//TODO configure serialization
//TODO configure deserialization
//TODO configure error handling
//TODO allow deserialization
