name: Create a Release Tag

on: [workflow_dispatch]

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Fail if branch is not main
        if: github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered on a branch other than main"
          exit 1

      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
          check-latest: true

      - name: Debug Settings
        run: mvn help:effective-settings
        
      - name: Calculate semantic version
        run: mvn --no-transfer-progress se.bjurr.gitchangelog:git-changelog-maven-plugin:1.96.1:semantic-version

      - name: Generate Changelog
        run: mvn --no-transfer-progress -Dfile=target/CHANGELOG.md se.bjurr.gitchangelog:git-changelog-maven-plugin:1.96.1:git-changelog

      - name: Configure Git
        run: |
          git config --global user.email "git@i3oot.de"
          git config --global user.name "i3oot"
            
      - name: Create Tag and Update Main-Branch
        run: |
          mvn --batch-mode --no-transfer-progress -DscmCommentPrefix="chore(release): :bookmark:" release:prepare
        env:  
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read value from Properties-file
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './release.properties'
          properties: 'scm.tag'

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.properties.outputs.scm-tag }}
          release_name: Release ${{ steps.properties.outputs.scm-tag }}
          body_path: target/CHANGELOG.md
          draft: true
          prerelease: false
